# Copyright 2019 Callum Iddon
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

task:
  name: publish
  only_if: $CIRRUS_BRANCH == "master"

  container:
    image: cirrusci/flutter:1.0.0

  env:
    matrix:
      - DIR: bloc_annotations
      - DIR: bloc_generator
      - DIR: flutter_bloc_provider

  copy_example_script: cp -r example $DIR

  script:
    - cd $DIR
    - yes | flutter packages pub publish
