name: bloc_annotations
description: >
    Annotations for the bloc_generator package that will generate BLoC
    architected code automatically.
version: 0.5.1
author: Callum Iddon <iddoncallum@gmail.com>
homepage: https://github.com/CallumIddon/bloc_generator/

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  meta: ^1.1.6
