targets:
  $default:
    builders:
      flutter_bloc:
        enabled: true

builders:
  flutter_bloc:
    import: "package:bloc_generator/bloc_generator.dart"
    build_extensions: {".dart": [".bloc.dart"]}
    builder_factories: ["bloc"]
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]